// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXhxL9VQt8Kp8s9R_XQEXIGJzxlsLp1E',
    appId: '1:394921406491:web:e43d742fad9bc9a286c8be',
    messagingSenderId: '394921406491',
    projectId: 'ducktogether-a1a42',
    authDomain: 'ducktogether-a1a42.firebaseapp.com',
    storageBucket: 'ducktogether-a1a42.appspot.com',
    measurementId: 'G-ZZ5F0EV362',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_MZG_ECOC9z-LB0HfPIvUwTf9sqOIL4',
    appId: '1:394921406491:android:eeafd9d7a2f6acc786c8be',
    messagingSenderId: '394921406491',
    projectId: 'ducktogether-a1a42',
    storageBucket: 'ducktogether-a1a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIRtvRysY_urZI3ty50otUzgAN2aJz_E',
    appId: '1:394921406491:ios:ada1031d8c27886b86c8be',
    messagingSenderId: '394921406491',
    projectId: 'ducktogether-a1a42',
    storageBucket: 'ducktogether-a1a42.appspot.com',
    iosBundleId: 'com.example.ducktogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpIRtvRysY_urZI3ty50otUzgAN2aJz_E',
    appId: '1:394921406491:ios:ada1031d8c27886b86c8be',
    messagingSenderId: '394921406491',
    projectId: 'ducktogether-a1a42',
    storageBucket: 'ducktogether-a1a42.appspot.com',
    iosBundleId: 'com.example.ducktogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkXhxL9VQt8Kp8s9R_XQEXIGJzxlsLp1E',
    appId: '1:394921406491:web:7a7edb43a9f67eb686c8be',
    messagingSenderId: '394921406491',
    projectId: 'ducktogether-a1a42',
    authDomain: 'ducktogether-a1a42.firebaseapp.com',
    storageBucket: 'ducktogether-a1a42.appspot.com',
    measurementId: 'G-RFHSMJT166',
  );
}
